aft_increase:
  name: "aft_increase"
  test_file: "../mei-data/raw_data/aft_increase/longformer_speaker/test.4096.jsonlines"
  test_file_mei: "../mei-data/raw_data/aft_increase/longformer_speaker/test.4096.mei.jsonlines"
  test_me: "../mei-data/raw_data/aft_increase/longformer_speaker/test_major_entities.jsonl"
  tsv: null
  cluster_threshold: 2