fantasy:
  name: "fantasy"
  train_file: "../data/raw_data/fantasy/longformer_speaker/train.4096.jsonlines"
  dev_file: "../data/raw_data/fantasy/longformer_speaker/dev.4096.jsonlines"
  test_file: "../data/raw_data/fantasy/longformer_speaker/test.4096.jsonlines"
  train_file_mei: "../data/raw_data/fantasy/longformer_speaker/train.4096.mei.jsonlines"
  dev_file_mei: "../data/raw_data/fantasy/longformer_speaker/dev.4096.mei.jsonlines"
  test_file_mei: "../data/raw_data/fantasy/longformer_speaker/test.4096.mei.jsonlines"
  train_me: ../data/raw_data/fantasy/longformer_speaker/train_major_entities.jsonl
  dev_me: ../data/raw_data/fantasy/longformer_speaker/dev_major_entities.jsonl
  test_me: ../data/raw_data/fantasy/longformer_speaker/test_major_entities.jsonl
  tsv: null
  cluster_threshold: 2