litbank:
  name: "litbank"
  train_file : "../mei-data/raw_data/litbank/longformer_speaker/0/train.4096.jsonlines"
  dev_file : "../mei-data/raw_data/litbank/longformer_speaker/0/dev.4096.jsonlines"
  test_file : "../mei-data/raw_data/litbank/longformer_speaker/0/test.4096.jsonlines"
  train_file_mei : "../mei-data/raw_data/litbank/longformer_speaker/0/train.4096.mei.jsonlines"
  dev_file_mei : "../mei-data/raw_data/litbank/longformer_speaker/0/dev.4096.mei.jsonlines"
  test_file_mei : "../mei-data/raw_data/litbank/longformer_speaker/0/test.4096.mei.jsonlines"
  train_me: "../mei-data/raw_data/litbank/longformer_speaker/0/train_major_entities.jsonl"
  dev_me: "../mei-data/raw_data/litbank/longformer_speaker/0/dev_major_entities.jsonl"
  test_me: "../mei-data/raw_data/litbank/longformer_speaker/0/test_major_entities.jsonl"
  tsv: "../mei-data/raw_data/litbank/tsv"
  cluster_threshold: 1