ontonotes:
  name: "ontonotes"
  train_file: "../mei-data/raw_data/ontonotes/longformer_speaker/train.4096.jsonlines"
  dev_file: "../mei-data/raw_data/ontonotes/longformer_speaker/dev.4096.jsonlines"
  test_file: "../mei-data/raw_data/ontonotes/longformer_speaker/test.4096.jsonlines"
  train_file_mei: "../mei-data/raw_data/ontonotes/longformer_speaker/train.4096.mei.jsonlines"
  dev_file_mei: "../mei-data/raw_data/ontonotes/longformer_speaker/dev.4096.mei.jsonlines"
  test_file_mei: "../mei-data/raw_data/ontonotes/longformer_speaker/test.4096.mei.jsonlines"
  train_me: ../mei-data/raw_data/ontonotes/longformer_speaker/train_major_entities.jsonl
  dev_me: ../mei-data/raw_data/ontonotes/longformer_speaker/dev_major_entities.jsonl
  test_me: ../mei-data/raw_data/ontonotes/longformer_speaker/test_major_entities.jsonl
  tsv: null
  cluster_threshold: 2