pride:
  name: "pride"
  test_file: "../mei-data/raw_data/pride/longformer_speaker/test.4096.jsonlines"
  test_file_mei: "../mei-data/raw_data/pride/longformer_speaker/test.4096.mei.jsonlines"
  test_me: "../mei-data/raw_data/pride/longformer_speaker/test_major_entities.jsonl"
  tsv: null